### ISSUE TITLE
SMA calculation is wrong

### ISSUE THREAD

**Issue by jvence** [mdeverdelhan/ta4j#107]
I noticed that the SMA calculations are incorrect. Here's my code:

```
ClosePriceIndicator closePrice = new ClosePriceIndicator(ts);

SMAIndicator smas = new SMAIndicator(closePrice,10);
            for (int x = 0; x < ts.getTickCount(); x++) {
                Decimal ind = smas[i].getValue(x);
                Tick t = ts.getTick(x);
       System.out.println(""+t.getEndTime().toLocalDate().toString(fmt)+","+t.getClosePrice().toDouble()+"," + ind);
            }
        }
```

The results appear in this CSV file (first column is the date, closing price and then SMA value): https://gist.github.com/jvence/388650586a3b63bb33fba4cdcad364c1 - The SMA values are wrong.

**Comment by sirajperson** [comment]
Can you please show the input data?

**Comment by sirajperson** [comment]
I copied your data and pasted it into OO_Calc (spreadsheet). I created a simple AVERAGE of the previous 10 lines, and pasted that cell down the list, and the data matches exactly. Items before your 10 period mark are not actually a 10 period SMA, because they do not yet have 10 data points. Please check out the pasted results here:

https://www.pastebucket.com/558375

You may want consider the following:

ClosePriceIndicator closePrice = new ClosePriceIndicator(ts);

SMAIndicator smas = new SMAIndicator(closePrice,10);
            for (int x = 0; x < ts.getTickCount(); x++) {
                Decimal ind = smas[i].getValue(x);
                Tick t = ts.getTick(x);
if(x>10)        
System.out.println(""+t.getEndTime().toLocalDate().toString(fmt)+","+t.getClosePrice().toDouble()+"," + ind);
            }
        }

**Comment by mdeverdelhan** [comment]
Thank you @sirajperson !

@jvence
It's a well-known problem. In the first periods, any indicator is in a stabilization phase. The results of our calculations may differ from other calculators for those first ticks.
BTW next tome please try to explain why you think the results are wrong (instead of just saying they're wrong). It would help US a lot (and may avoid a question because, in this case, they aren't... in our context).

**Comment by jvence** [comment]
This definitely should not be closed yet.

Firstly, the data I gave you are listed from most recent dates so the first
10 SHOULD have a 10-day moving average (BTW, this is data for $AAPL stock).

The correct SMAs are as follows:

22-Sep-16

114.62

111.41

21-Sep-16

113.55

110.50

20-Sep-16

113.57

109.98

19-Sep-16

113.58

109.39

16-Sep-16

114.92

108.81

15-Sep-16

115.57

107.99

14-Sep-16

111.77

107.04

13-Sep-16

107.95

106.47

12-Sep-16

105.44

106.35

9-Sep-16

103.13

106.50

8-Sep-16

105.52

106.95

7-Sep-16

108.36

107.20

6-Sep-16

107.7

107.25

2-Sep-16

107.73

107.33

1-Sep-16

106.73

107.49

31-Aug-16

106.1

107.73

30-Aug-16

106

108.04

29-Aug-16

106.82

108.38

26-Aug-16

106.94

108.64

25-Aug-16

107.57

108.77

24-Aug-16

108.03

108.80

23-Aug-16

108.85

108.80

22-Aug-16

108.51

108.80

19-Aug-16

109.36

108.78

18-Aug-16

109.08

108.59

17-Aug-16

109.22

108.27

16-Aug-16

109.38

107.93

15-Aug-16

109.48

107.44

12-Aug-16

108.18

107.10

11-Aug-16

107.93

106.70

10-Aug-16

108

106.34

9-Aug-16

108.81

105.84

8-Aug-16

108.37

104.62

5-Aug-16

107.48

103.52

4-Aug-16

105.87

102.64

3-Aug-16

105.79

101.99

2-Aug-16

104.48

101.41

1-Aug-16

106.05

100.95

29-Jul-16

104.21

100.33

28-Jul-16

104.34

99.78

27-Jul-16

102.95

99.23

26-Jul-16

96.67

98.62

25-Jul-16

97.34

98.70

22-Jul-16

98.66

98.66

21-Jul-16

99.43

98.46

20-Jul-16

99.96

98.11

19-Jul-16

99.87

97.67

18-Jul-16

99.83

97.18

15-Jul-16

98.78

96.79

14-Jul-16

98.79

96.47

13-Jul-16

96.87

96.03

12-Jul-16

97.42

95.70

11-Jul-16

96.98

95.16

8-Jul-16

96.68

94.81

7-Jul-16

95.94

94.75

6-Jul-16

95.53

94.71

5-Jul-16

94.99

94.75

1-Jul-16

95.89

94.76

30-Jun-16

95.6

94.70

29-Jun-16

94.4

94.90

28-Jun-16

93.59

95.17

27-Jun-16

92.04

95.56

24-Jun-16

93.4

96.09

23-Jun-16

96.1

96.63

22-Jun-16

95.55

96.99

21-Jun-16

95.91

97.33

20-Jun-16

95.1

97.64

17-Jun-16

95.33

97.99

The issue is that the library is assuming that the TimeSeries is sorted
from oldest to most recent. Wondering if system should sort the time series
before calculation.

**Comment by mdeverdelhan** [comment]
Yes, ta4j is assuming the TimeSeries is "sorted" from oldest to most recent, because we assume that time goes from past to present.

There is no chance that we implement a way to "revert" the order of the series before the calculation. Because:
  
  * In an ideal world the "order" must not change the result of the calculation.
  * Numerous indicators are recursive and use the results of the previous ticks to get calculated (see the EMA for instance).
  * With the most recent first, in particular circumstances, some recent results may be less accurate than the oldest (not sure about this one).
  
If you present the most recent first I suggest you to calculate your results, then get them in reverse order by calling `sma.getValue(series.getTickCount())`, `sma.getValue(series.getTickCount()-1)`, ...
