### ISSUE TITLE
Is there a way to get all ticks in a array ?

### ISSUE THREAD

**Issue by yellowbean** [mdeverdelhan/ta4j#115]
Hi, Verdelhan

Do you think it is a good idea to add a "getTicks" to TimeSeries ? if a user want to analysis like, calculate the variance of all prices of a time series ?

I found there is existing a "getTick(int i) " ,but user have to construct a for loop to retrieve all the ticks.

Pls kindly let me know your idea, thanks & great job~

**Comment by sirajperson** [comment]
I agree. I also think that would be helpful. Passing all ticks as an object would be much more efficient than creating an external loop to extract the ticks from the protected object.

**Comment by mdeverdelhan** [comment]
Since you feed the TimeSeries object, it is up-to-you to manage your ticks as you want. Ta4j does not manage ticks, it just performs calculations on them. By the way it would raise lots of questions regarding the moving time series (with the eviction mechanism).

**Comment by sirajperson** [comment]
Interesting, managing ticks is exactly what the time series does. That is why it has a removedTicks variable, which kind of doesn't make it a "moving" series actually since its constricted to the unsigned int primitive range. Anyhow, creating a getter for the <tick> object as a whole from the TimeSeries seems only natural.

**Comment by mdeverdelhan** [comment]
See the TimeSeries object as a view of a sequence of ticks. The removedTickCount / maximumTickCount variables are just here to limit the memory usage on live trading. Ideally TimeSeries should be an interface.
