### ISSUE TITLE
CsvTradesLoader not handling reverse-order CSV content.

### ISSUE THREAD

**Issue by ClydeMachine** [mdeverdelhan/ta4j#119]
The examples provide a means by which a user of ta4j can populate a TimeSeries with data about trades, as built in [CsvTradesLoader.java](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/loaders/CsvTradesLoader.java). The code catches instances whereby the first line read in from the input (the first line of the CSV file) represents the last trade in the series, and reverse the ```beginTime``` and ```endTime``` variables accordingly. However, in such cases where this occurs (where the CSV file has the latest data first in the file and has the oldest trades at the very tail of the file), the code does not handle the fact that the List ```lines``` needs to be reversed before we populated the ```ticks``` with its data. The resulting tick data is then in reverse order, causing technical indicators to calculate backward results.

I can produce a PR for this but wanted to get an Issue in ahead of time.

**Comment by sirajperson** [comment]
I thought that the examples were kinda conceptual guide lines rather than definitive solutions to all situations. In such a case where you have some data that is ascending, I would always just create a skeleton  object and de-increment through it. 

Also, the loading of the file is the least of the algorithmic issues with the examples... the fact that there is a buildEmptyTicks function is rather process intensive for doing optimization searches over historical data as well... but again, I think it is pertinent that the reader take it as exactly what it is, an example, rather than a solution.

**Comment by ClydeMachine** [comment]
Valid points. While the examples don't appear to be a be-all-end-all, and are certainly not the most efficient way to construct a TimeSeries out of historical data, I find it would be worthwhile to ensure they're at least complete in what they're presenting. As long as code was written checking for a ascending vs descending dataset, it should go all the way to completion.

To that end I'll go ahead and create a PR for it and let the decision be made at that point.

**Comment by mdeverdelhan** [comment]
Accepted. Thank you @ClydeMachine. :)
