### ISSUE TITLE
Incorrect use of the name 'Tick' Should be 'Bar'

### ISSUE THREAD

**Issue by marshallgs** [mdeverdelhan/ta4j#139]
Nice codebase! One thing: You define a tick as open/high/low/close/volume data, but that is incorrect. please take a look at investopedia.com. A tick is a trade, usually the last trade placed, which means it contains: price, quantity, timestamp, symbol at minimum. What you call a 'tick' is in fact a 'bar'. You should consider renaming to fix that as it creates confusion when trying to use the javadocs.

**Comment by mdeverdelhan** [comment]
"Bar" comes with a graphical meaning. And for now I don't want to reduce the tick concept to its graphical part. I agree that the name is not perfect but I did not find another better one. I see it like a clock tick with OHLCV for the preceding period.

**Comment by mattgreenuk** [comment]
I see why you wouldn't want to change it (after all, it's pretty embedded into the codebase) but I do agree with @marshallgs that it is confusing given that "tick" is so widely used across the industry.

Internally to my own system I've used Price to mean the instantaneous prices from the market (actually containing a bid & an offer price) and PeriodicPrice to mean the OHLCV or tick as per the ta4j parlance.

My PeriodicPrice has open, high, low & close fields plus start and end date-times - in effect they reprsent a summary over the period (end minus start).

These are often called Candles (due to their shape on the graph).

Looking at ta4j I think `Trade` models the real-world tick-prices.

**Comment by magick93** [comment]
I can see that Bar has a graphical meaning, or reference. However I think this is a minor issue, and I think Tick and Bar are well known and understood.

Here are some alternative terms that you may wish to consider

- Quote or PriceChangeEvent
- Window - a more tech specific term for a time span of data - as an alternative to Bar. Alternatively OHLC.

**Comment by mdeverdelhan** [comment]
Transfered to https://github.com/ta4j/ta4j/issues/9.
