### ISSUE TITLE
Join ticks

### ISSUE THREAD

**Issue by wellingtonwrs1** [mdeverdelhan/ta4j#141]
Hi, I would like to know if there is any functionality that takes x quantity of ticks and turns it into a single tick. Example:
[Time: 16/05/2017 10:05:00, close price: 1,107730]
[Time: 16/05/2017 10:05:05, close price: 1,107810]
[Time: 16/05/2017 10:05:10, close price: 1,107740]
[Time: 16/05/2017 10:05:15, close price: 1,107705]
[Time: 16/05/2017 10:05:20, close price: 1,107675]
[Time: 16/05/2017 10:05:25, close price: 1,107705]
[Time: 16/05/2017 10:05:30, close price: 1,107730]
[Time: 16/05/2017 10:05:35, close price: 1,107700]
[Time: 16/05/2017 10:05:40, close price: 1,107655]
[Time: 16/05/2017 10:05:45, close price: 1,107665]
[Time: 16/05/2017 10:05:50, close price: 1,107620]
[Time: 16/05/2017 10:05:55, close price: 1,107625]
[Time: 16/05/2017 10:06:00, close price: 1,107605]

To:

[Time: 16/05/2017 10:06:00, open price: 1,107730, close price: 1,107605]

**Comment by mdeverdelhan** [comment]
There is not. For now it is up-to-you to build a correct TimeSeries.

**Comment by team172011** [comment]
I had to aggregate daily candlestick data to weekly, monthly, quarterly and yearly 'ticks'. At the moment i calculate this in R because i have been difficult with those different time levels and its relation. If you just want to aggragate each x ticks (irrespective of underlying week, year, etc.) you can implement your case as indicator like:

>  'AggragateTicksIndicator(TimeSeries series, int x)'

 to aggregate  each x Ticks of TimeSeries series. This would be easy to implement: in your case you could get as output 13 ticks with same values (first(open) ,last(close),  sum(volume), etc)

My case is a little bit more complicated because you can not just aggragate each x ticks, but have to be sure that you have the right data for a week, month, quarter and year which are continuously changing intervalls in dependence of current calendar year, public holidays and so on.  I would be happy about a solution approach (librarys?) in Java. (In R i can use packages data.table and lubridate to do this relative easy and fast for a lot of ticks)

**Comment by martinklepsch** [comment]
I guess this can also be closed and is "left to the end user" for now?

**Comment by mdeverdelhan** [comment]
@team172011 I like your AggregateTicksIndicator idea but I don't want to implement such date management/checking. Too many weird cases (daylight savings, midnight, time origins, ...).

**Comment by team172011** [comment]
@mdeverdelhan yes, same with Pivot Points indicator...
