### ISSUE TITLE
IndexOutOfBoundsException with TimeSeries#setMaximumTickCount

### ISSUE THREAD

**Issue by sirilicious** [mdeverdelhan/ta4j#176]
I'm receiving an `IndexOutOfBoundsException` when running a `Strategy` using `TimeSeries#setMaximumTickCount`.

I limit the `TimeSeries`to 500 preventing excessive memory consumption during the live trading (as taken from the [wiki](https://github.com/mdeverdelhan/ta4j/wiki/Live%20trading)).

In addition, I not only use `Strategy#shouldEnter`, but also the `TimeSeries#run` to verify the overall performance. Unfortunately I get following error:
```
2017-08-25 09:06:41,786 ERROR [stderr] (Thread-97) 	at java.lang.Thread.run(Thread.java:748)
2017-08-25 09:06:41,786 ERROR [stderr] (Thread-97) Caused by: java.lang.IndexOutOfBoundsException: Index: 528, Size: 500
2017-08-25 09:06:41,786 ERROR [stderr] (Thread-97) 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
2017-08-25 09:06:41,786 ERROR [stderr] (Thread-97) 	at java.util.ArrayList.get(ArrayList.java:429)
2017-08-25 09:06:41,786 ERROR [stderr] (Thread-97) 	at eu.verdelhan.ta4j.TimeSeries.run(TimeSeries.java:418)
2017-08-25 09:06:41,787 ERROR [stderr] (Thread-97) 	at eu.verdelhan.ta4j.TimeSeries.run(TimeSeries.java:400)
2017-08-25 09:06:41,787 ERROR [stderr] (Thread-97) 	at eu.verdelhan.ta4j.TimeSeries.run(TimeSeries.java:388)
2017-08-25 09:06:41,787 ERROR [stderr] (Thread-97) 	...
```

How can I prevent this from happening?
Thanks!

**Comment by martinklepsch** [comment]
I think this might be a bug:

- when adding ticks using `TimeSeries#addTick` the `endIndex` is incremented
- then `removeExceedingTicks()` is called which removes ticks but does not update `endIndex`

**Comment by mdeverdelhan** [comment]
Using `0.9-SNAPSHOT`? Could you give us a [SSCCE](http://sscce.org/)?

@martinklepsch Why would you want to update the `endIndex` in `removeExceedingTicks()`?

**Comment by martinklepsch** [comment]
I think I maybe didn't fully understand the code. 🙈 I thought `endIndex` should always be equal to the number of ticks in a timeseries but it seems that begin and endIndex can also be greater than 0 or greater than the number of ticks respectively.

**Comment by TheCookieLab** [comment]
Let's say you start with a TimeSeries of 10 ticks. beginIndex == 0 and endIndex == 9. Now we set the maximum tick count to 5 so after removing the first 5 ticks, endIndex still == 9. 

Now if we run a strategy and loop from beginIndex to endIndex (0-9), we get an IndexOutOfBoundsException since there's only 5 ticks left (0-4).

**Comment by mdeverdelhan** [comment]
You are not supposed to run your strategy at removed tick indexes after setting a maximum tick count. Initialize your indicators on those ticks, then AFTER, you can call setMaximumTickCount, and then, you can run your strategy at endIndex (because you are now on a moving time series).

**Comment by TheCookieLab** [comment]
Well, I didn't know we weren't suppose to run strategies on limited time series. Perhaps there could be an exception or error returned in that case (i.e. if max tick count has been set, the run() methods log an error and return immediately or throw an exception). 

An analogy could be, I'm not supposed to click "Submit Order" more than once, but if I do and it causes Amazon to create multiple orders, that's a problem :)

**Comment by mdeverdelhan** [comment]
@TheCookieLab Yes you are right. An exception should be thrown in that case.
For information, the setMaximumTickCount is supposed to be used in a real trading session to avoid a too big memory consumption, while the run() methods are provided for the backtesting phase (for real trading you have to implement your own run() method because it is up-to-you to manage your entries/exits).

Please continue this thread on the new repo: https://github.com/ta4j/ta4j
