### ISSUE TITLE
Time scale in time series

### ISSUE THREAD

**Issue by ecorderob** [mdeverdelhan/ta4j#29]
The problem I am facing is that I want to show weekly charts in my web page, but I am downloading data from a provider which only returns daily data. It would be nice if you could create the TimeSeries with daily data and then call to a function which would return weekly data instead of daily.

**Comment by mdeverdelhan** [comment]
OK I better understand.

You have to build your weekly ticks by yourself. I made [an example](https://github.com/mdeverdelhan/ta4j/blob/ta4j-0.6/ta4j-examples/src/main/java/ta4jexamples/loaders/CsvTradesLoader.java) of how you can build 5-minutes ticks directly from trades. You can take your inspiration from it (as you just have to create a tick on each 7 days).

For now I won't look deeper into this because I don't know how to do it simply and if it's worthwhile (because it would need numerous tests and API questioning). But if you're enough motivated to make a pull request I'll gladly study it.
