### ISSUE TITLE
TimeSeries length or size

### ISSUE THREAD

**Issue by sgrotz** [mdeverdelhan/ta4j#30]
Hey, 
First of all - thanks for the great work! Love this project - have it embedded in the myopentrader engine for quite some time. 

I noticed that you never return the length/size of the timeSeries? In a lot of cases, I need to convert my data into a timeSeries, but I am only interested in the last one or two elements (without knowing, how many ticks are within one timeSeries at a time). I forked your repository, to add the
    public int size() {
    	return ticks.size();
    }
to the TimeSeries class. Did u not add it because it may contain stale data during caching?

Thanks :)
Stephan

**Comment by mdeverdelhan** [comment]
Hi,

Thank you for using ta4j.

I don't know if you noticed but there's already a [TimeSeries#getTickCount()](https://github.com/mdeverdelhan/ta4j/blob/ta4j-0.6/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L165) method. Wouldn't it be enough?
I think it may fit your needs. Also:

```java
// To get the last two ticks:
series.getTick(series.getEnd()-1);
series.getTick(series.getEnd()); // Or series.getLastTick();

// To get a sub-series composed of the last two ticks
TimeSeries subseries = series.subseries(series.getEnd()-1, series.getEnd());
```

If not, then I didn't understand, please explain more in details.

Also it can't return a simple `ticks.size()` because:
  * indeed I can't garantee the consistency with caching and/or when it's a moving time series (see [TimeSeries#setMaximumTickCount(int maximumTickCount)](https://github.com/mdeverdelhan/ta4j/blob/ta4j-0.6/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L217)
  * it would return a wrong result for sub-series as they are _views_ of the original one (see [TimeSeries#subseries(int beginIndex, int endIndex)](https://github.com/mdeverdelhan/ta4j/blob/ta4j-0.6/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L281))

By the way I don't like terms like _length_ or _size_ as they are too generic (in this case).

Marc

**Comment by sgrotz** [comment]
Thanks Marc for your help, 
I am seriously wondering why I didnt see the getTickCount method. Must have slipped my mind ... that is awesome, I will update my code for that.
