### ISSUE TITLE
Improve strategy building engine

### ISSUE THREAD

**Issue by mdeverdelhan** [mdeverdelhan/ta4j#32]
The current strategy building engine is a mess.
It comes with several problems, of which:
  * There is no simple way of building an entry strategy independently of an exit strategy.
  * In some case we may use entry rules in exit strategy (and reciprocally), the engine doesn't allow this easily.
  * For each strategy provided by ta4j we don't know, a priori, if it's a more-entry strategy, a more-exit one, or a both one.

I plan to refactor all the strategy building engine. I would keep the strategy concept but they would be constructed with an entry rule and an exit rule. Each rule will be truly independent of each other.

**Comment by mdeverdelhan** [comment]
Using separated entry/exit rules makes harder to refactor strategies like `NoSoFastStrategy`, `StopGainStrategy` or `StopLossStrategy` (which all need at least the index/price of the last operation).
In order to solve this problem I plan to give the record of current trading session to the strategy/rule each time we should enter/exit. It would also gives more flexibility for implementations of complex trading rules. This trading record/history would mainly be a list of executed Trades, thus it may be usable everywhere we need a List<Trade> (such as analysis criteria).

**Comment by npapula** [comment]
I agree that that the current Strategy usage is not very clear.

Would it be sufficient to have:
TimeSeries.run(entryStrategy, exitStrategy)

This would allow also:
TimeSeries.run(oneStrategy, oneStrategy)

In this way there would not have to be a new concept "Rule", i.e. the library would be simpler and clearer. I think this would also reduce the number of required changes.

Each Strategy implementation would be responsible to tell in its documentation how it should be used, i.e. does it provide entry or exit signals or both.

I also think that there should be a possibility to use Trade objects without a TimeSeries. One use case would be analyzing trades read from broker's report without access to actual rate ticks. Actually I just did this by using Ticks instead of Trades which was very confusing and inconvenient (I drew a OHLC chart of actual trades). And why not change Trade to an interface, to allow a Trade to both contain its open and close values and allowing them to be read from TimeSeries, depending on the situation.

**Comment by mdeverdelhan** [comment]
Yes, `TimeSeries.run(entryStrategy, exitStrategy)` could be sufficient. But I would prefer `TimeSeries.run(entryRule, exitRule)` since I consider a Strategy to be a pair of rules (one for the entry, the other for the exit). SoI keep `TimeSeries.run(strategy)` as is: it avoids giving two arguments of the same type to the `run` method. It's also more convenient to use for comparison of analysis criteria.

Numerous changes in the API don't afraid me. By the way it's not the part which introduces the most of changes: the trading `Rule`s is just replacing the `Strategy` concept (i.e. everywhere except when I need a pair of rules).
The biggest changes come from the new `TradingRecord` object, which has to be passed to the rules in order to get information about the previous trades. This information was missing with the previous Strategy implementation and might conduce to erroneous results.

I don't like the idea of having strategies providing entry or exit signals or both. It comes with numerous questions like: How to compare an exclusively exit strategy with an exclusively entry one? How to run an exclusively exit strategy? Etc. I think it's much simpler if we assume that a Strategy is just a pair of an entry Rule and an exit Rule.

Your last comment makes me think your use case is a bit weird. If you want to draw a classic OLHC chart you have to provide the ticks. Why do you want to display your operated trades on that chart? Is it to display the cash flow? Then there is already [an example for that](https://github.com/mdeverdelhan/ta4j/wiki/Usage-examples#analysis).
Finally if you really want to draw trade-related stuff on a chart I'm currently adding a `TradingRecord` object, which is approximately a time series for actual trades. It will help for that kind of requirements. I will update the examples with that.

**Comment by npapula** [comment]
If I understood correctly, TradingRecord would be a list of Trades. That is definitely a good thing.

**Comment by npapula** [comment]
I plotted historical trades in OHLC chart to analyze opportunities for improvement. For example, in the chart I easily spotted a period of trades that had been well in profit but were eventually closed at loss. From this I concluded that trade entries had been good but exiting trades needed improvement.

As you can see from the above real-life example, there is also a use case for testing different entry strategies/rules with different exit strategies/rules. Therefore I suggest implementing EntryRule and ExitRule as interfaces because this gives a lot of flexibility in their implementations. Then you could also avoid calling 
TimeSeries.run(EntryRule, ExitRule)
with two arguments of the same type while at the same time offering an easy way to test different EntryRule and ExitRule combinations. And have also 
TimeSeries.run(Strategy)

As you wrote, defining Strategy as including (or implementing!?) both EntryRule and ExitRule is definitely not a bad option.

**Comment by npapula** [comment]
BTW now TimeSeries is defined differently from how it is usually understood e.g. in applied mathematics. Please see http://en.wikipedia.org/wiki/Time_series. For my own use I actually wrote an interface NumericalTimeSeries that corresponds to the common definition. Of course, the benefit is that I can more easily use common time series analysis and statistical methods that are freely available e.g. in Apache. Sometimes I have seen the current definition of TimeSeries to be called as TickSeries. If you are not afraid of changing class/interface names then I would suggest to consider that, both to adhere to common definition of time series and to make the API easier to understand for those familiar with statistics and time series analysis.

**Comment by mdeverdelhan** [comment]
Some thoughts:

1) [`TradingRecord` is a list of Trades](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/TradingRecord.java). It also contains a list of orders, a list of entries, a list of exits, etc. I will deploy the snapshot when I get my Debian fully functional.

2) I made [an example](http://github.com/mdeverdelhan/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/analysis/BuyAndSellSignalsToChart.java) to plot your trades over the tick prices. Doesn't it fit your needs? (Except that it's not an OHLC, but it should not be difficult to transform it)
BTW if you want to test different entry rules with different exit rules, you can do it like this:

    Rule[] entryRules = new Rule[] {
        new FixedRule(0, 1, 2),
        BooleanRule.TRUE.xor(BooleanRule.FALSE),
        new JustOnceRule()
    };
    Rule[] exitRules = new Rule[] {
        BooleanRule.TRUE,
        new FixedRule(5, 7, 9)
    };
    for (Rule entryRule : entryRules) {
        for(Rule exitRule : exitRules) {
            timeSeries.run(new Strategy(entryRule, exitRule));
        }
    }
	
3) I like your last comment about the naming of TimeSeries. Of course in our context the meaning of "time series" is reduced to the one often used for quantitative finance. I have read several websites as references for the financial domain and they are using this definition. Also, initially I modified an existing lib called Tail (http://sourceforge.net/projects/tail/). Nowadays ta4j is fundamentally different (since I changed approximately everything) but I kept the name they had chosen.
But you are right. Renaming that class to TickSeries may be an option. It gains ground in my mind, I will consider it.

**Comment by mdeverdelhan** [comment]
@npapula Also could you provide some valuable pointers where our definition of TimeSeries is called as TickSeries?

**Comment by npapula** [comment]
TradingRecord is a very intuitive and clean concept! Good idea to include also Orders.

Using the strategy is clearer now. However, I noticed one problem that you wanted to avoid. Currently you call Strategy constructor with two parameters of the same type, namely Rule. You said you wanted to avoid calling with two parameters of the same type: solution would be (as earlier mentioned) having two interfaces, EntryRule and ExitRule. This would also force writing "self-documenting code". And it also gives some freedom in the implementation: some class might implement complicated logic for mutually depending entries and exits and it could implement both EntryRule and ExitRule.

BTW1 I wonder what is the reason for requiring every Rule to implement e.g. "and", "or" etc. Sorry if I prematurely comment code that you are still modifying!

BTW2 In TradingRecord I noticed one issue which at least currently does not affect my usage but potentially would be important to someone else: TradingRecord currently assumes one open Trade. I think it should allow 0...N open trades at the same time.

**Comment by npapula** [comment]
My use case when analysing trades is:
I have access to broker's report which contains prices for
* trade entry price
* trade exit price
* highest price while trade was open
* lowest price while trade was open
In this use case I don't have access to ticks/prices. Therefore I think Trade should contain all the above fields. Especially when the trade entry/exit price is usually different from the Order's price or the corresponding Tick. So, from my point of view TradingRecord should be independent from Ticks. This is also the reason why your example does not work for me. BTW I assume quite many users do not have access to prices, only to broker report.

**Comment by npapula** [comment]
About term "TickSeries":
Originally I bumped into the term "TickSeries" in some charting package. However, it seems the term is used less often. I noticed this
http://se.mathworks.com/help/finance/ret2tick.html
where TickSeries seems to be the same as "PriceSeries". Apparently PriceSeries is more widely used but I did not find it in Investopedia. So, I am a little confused. This is the  Investopedia definition for TimeSeries: http://www.investopedia.com/terms/t/timeseries.asp

Based on e.g. Investopedia name "OhlcSeries" would be conceptually quite clear:
http://www.investopedia.com/terms/o/ohlcchart.asp
http://www.jfree.org/jfreechart/api/javadoc/org/jfree/data/time/ohlc/OHLCSeries.html

**Comment by mdeverdelhan** [comment]
1) About EntryRule/ExitRule

Yes, I said I wanted to avoid giving two parameters of the same type *to the [`TimeSeries#run()`](http://github.com/mdeverdelhan/ta4j/blob/ta4j-0.6/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L378) method*. For me there is a strong difference between a method call and a constructor.
That being said, we may discuss having two interfaces, `EntryRule` and `ExitRule`.
+1 for the "self-documenting code". However I don't have any use case in mind for having a class which would implement both EntryRule and ExitRule. The only case I can imagine is if some conditions are shared between the entry rules and the exit rules. In that situation I think the best option is to have an intermediate class to do the job.
I use the [`TradingRecord`](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/TradingRecord.java) object for mutually depending entries and exits (see the simple [`WaitForRule`](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/WaitForRule.java#L53) class).
Except their name, what would be the fundamental differences between EntryRule and ExitRule? How to provide the ability to combine several rules using methods like [`and()`](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/Rule.java#L38), [`or()`](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/Rule.java#L44), etc.? Should a class implementing both EntryRule and ExitRule have to implement both `EntryRule#add(EntryRule)` and `ExitRule#add(ExitRule)` methods?

2) About the current architecture for trading rules

I used the [specification pattern](http://en.wikipedia.org/wiki/Specification_pattern) for the trading rules. It involves to give to each rule the ability to be combinated with any other rule using logical operators. Those operators are those [`and()`](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/Rule.java#L38), [`or()`](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/Rule.java#L44), etc. methods. You don't have to implement them: you can extend [`AbstractRule`](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/AbstractRule.java) to avoid that.

3) About `TradingRecord`

In fact, TradingRecord doesn't assume one open Trade, but 0 or 1. It always has [its "current trade"](http://github.com/mdeverdelhan/ta4j/blob/adfb00d80bed15a8a4d933ddb680a288f2d0cf28/ta4j/src/main/java/eu/verdelhan/ta4j/TradingRecord.java#L108) which is open only if its entry order has been operated. It may be interesting to allow N open trades but:

  * I don't need this feature.
  * It would be a huge refactoring and I don't have enough time for that.

4) About your use case

In fact `TradingRecord` is independent from Ticks. For instance, in a trading bot, the strategy gives you a "shouldEnter" information, then it's up to you to call the `TradingRecord#operate()` method with the price you really spent (see [this example](http://github.com/mdeverdelhan/ta4j/blob/8690000173256872a5b01410d3d4a024ae31a47f/ta4j-examples/src/main/java/ta4jexamples/bots/TradingBotOnMovingTimeSeries.java#L143)).
However, in the `TimeSeries#run()` method I chose to automatically use the close price of the current tick since I don't have any other information.
I don't know how to address your problem simply. I will think about it.

5) About TimeSeries/TickSeries:

I don't like "OhlcSeries", since it's less readable and sounds less clearly for newcomers.
I see an advantage of calling that "TickSeries": it immediately appears that it's a series of Ticks. But as you pointed it out, the term is not often used. For now I keep the change in a local branch.

**Comment by npapula** [comment]
1) About rules:
The following interface would force every rule-implementation to clearly document its capabilities and at the same time be the simplest possible.

public interface EntryRule {
    /**
     * @param index the tick index
     * @return true if this rule is satisfied for the provided index, false otherwise
     */
    boolean shouldEnter(int index);
    
    /**
     * @param index the tick index
     * @param tradingRecord the potentially needed trading history
     * @return true if this rule is satisfied for the provided index, false otherwise
     */
    boolean shouldEnter(int index, TradingRecord tradingRecord);
}

And similarly for ExitRule (with "shouldExit" as function name).

For combining different rules (e.g. with AND, OR, etc.) I would use a separate class(es) and not include them in the interface. This is mainly because (at least for me) there would be several ways to combine different rules, not only AND, OR, etc. I find it less clear that some rule combinations would be in the interface, and some combinations outside interface. Using separate class also makes the Rule (or EntryRule and ExitRule) simpler and conceptually clearer (as in the code snippet above). It would also give freedom to implement the interface in any way without extending AbstractRule (to implement AND, OR, etc. -functions that might not be needed). Actually, having to extend AbstractRule reduces the flexibility of using interfaces.


2) About my use case:
TradingRecord#operate contains parameter index that does not exist in my use case.

Here are the classes/interfaces that I currently use for my use case. I am trying to get rid off my own classes and start to use yours. Can you see if/how your "Trade" could possibly be changed to implement my "ReadonlyTrade" and provide a constructor for defining all the fields!?


/**
 * 
 */
package ta4j.augmentation;

import org.joda.time.DateTime;

import eu.verdelhan.ta4j.Decimal;
import eu.verdelhan.ta4j.OperationType;

/**
 * Represents a single trade. The trade may start with BUY or SELL, it may be open or closed, etc.
 * 
 * This interface is independent from other interfaces and classes, i.e. it does not 
 * use other classes for any purpose (expect DateTime from Joda and primitive classes).
 * 
 * @author Niko Papula
 *
 */
public interface ReadonlyTrade {

	/**
	 * 
	 * @return unique id
	 */
	public String getId();
	
	/**
	 * returns profit of this trade. Returns NaN if profit can not be calculated. 
	 */
	public Decimal getProfit();
	
	/**
	 * @return time when trade was opened
	 */
	public DateTime getOpeningTime();
	
	/**
	 * @return time when trade was closed
	 */
	public DateTime getClosingTime();
	
	/**
	 * @return ticker symbol of the issue that was traded
	 */
	public String getTickerSymbol();
	
	/**
	 * @return volume of this trade (without any information about the volume unit)
	 */
	public Decimal getVolume();
	
	/**
	 * @return min observed price while the trade was open
	 */
	public Decimal getMinPrice();

	/**
	 * @return max observed price while the trade was open
	 */	
	public Decimal getMaxPrice();
	
	/**
	 * @return the entry/opening price of this trade
	 */	
	public Decimal getOpeningPrice();

	/**
	 * @return the exit/closing price of this trade
	 */		
	public Decimal getClosingPrice();

	/**
	 * @return the entry operation, i.e. BUY or SELL
	 */			
	public OperationType getOpeningOperation();

	/**
	 * @return the exit operation, i.e. BUY or SELL, opposite to getEntryOperation
	 */	
	public OperationType getClosingOperation();
	
	/**
	 * @return true is trade is close, otherwise false
	 */
    public boolean isFinished();

    /**
     * @return true if the trade is still open, false otherwise
     */
    public boolean isOpen();

    /**
     * @return true if the trade is closed, false otherwise
     */
    public boolean isClosed();    
    
    /**
     * @return true if the trade is new (i.e. not opened and not closed), false otherwise
     */
    public boolean isNew();


    
	public boolean equals(Object obj);
	public int hashCode();
    public String toString();
}


package ta4j.augmentation;

import java.util.ArrayList;

import eu.verdelhan.ta4j.Decimal;

/**
 * Contains list of trades in any order. I.e. the order of trades is not fixed.
 * 
 * Although this object implements NumericalTimeSeries, this is not a time series in its 
 * usual sense. The index in this object does not represent time but merely index of a 
 * trade. I.e. the time difference between the trades may vary. 
 * 
 * The contained trades need to to be ordered by time manually if they are required to be 
 * in ascending/descending time order. 
 * 
 * @author Niko Papula
 *
 */
public class TradeList extends ArrayList<ReadonlyTrade> implements NumericalTimeSeries {

	/**
	 * 
	 */
	private static final long serialVersionUID = -447015717500160132L;

	public void printIds() {
		System.out.println("start");
		for (int i = 0; i < size(); i++) {
			System.out.println(get(i).getId());
		}
		System.out.println("end");		
	}
	
	/**
	 * @return average profit of profitable trades
	 */
	public double getAverageProfit() {
		double result = 0.0;
		int count = 0;
		for (int i = 0; i < size(); i++) {
			if (get(i).getProfit().toDouble() > 0.0) {
				result = result + get(i).getProfit().toDouble();
				count++;
			}
		}
		
		return result / (double) count;
	}

	/**
	 * @return average loss of losing trades
	 */	
	public double getAverageLoss() {
		double result = 0.0;
		int count = 0;
		for (int i = 0; i < size(); i++) {
			if (get(i).getProfit().toDouble() <= 0.0) {
				result = result + get(i).getProfit().toDouble();
				count++;
			}
		}
		
		return result / (double) count;
	}	
	
	@Override
	public Decimal getDecimal(int index) {
		return this.get(index).getProfit();
	}

	@Override
	public double getDouble(int index) {
		return this.get(index).getProfit().toDouble();
	}

	@Override
	public double[] getDataAsArray() {
		double[] result = new double[size()];
		
		for (int i = 0; i < size(); i++) {
			result[i] = getDouble(i);
		}
		
		return result;
	}
}


package ta4j.augmentation;

import eu.verdelhan.ta4j.Decimal;

/**
 * Provides simple access to time series, i.e. series of values per index.
 * 
 * Time series is here understood as is usual in e.g. statistics or applied mathematics, i.e. 
 * as a series of numerical values taken at fixed time intervals. For example, as temperature every day at 12,
 * number of people in a shop at every full hour, etc.
 * 
 * This interface is intended to provide the minimal necessary functionality for time series analysis.
 * 
 * @author Niko Papula
 */
public interface NumericalTimeSeries {
	
//	public String getTitle();
//	public Date getStartDateTime();
//	public Date getEndDateTime();
	
	public int size();

	public Decimal getDecimal(int index);
	
	public double getDouble(int index);
	
	public double[] getDataAsArray();
}
