### ISSUE TITLE
About common interface for TimeSeries and Indicator<Decimal>

### ISSUE THREAD

**Issue by npapula** [mdeverdelhan/ta4j#33]
The library now contains TimeSeries and Indicator<Decimal>. They both offer access to values by index. So, they actually provide the same functionality.

AnalysisCriterion inferface is very good because it offers an easy way to write different implementations for different criteria. However, the AnalysisCriterion always requires TimeSeries to calculate values.

I would like to use AnalysisCriterion to calculate values from some Indicators. I think creating a common interface for both TimeSeries and Indicator<Decimal> would simplify the code and make it easier to use. I could e.g. calculate total profit using either average or close values by just creating a new indicator. I might also want to calculate AnalysisCriterion from a couple of indicators, e.g. an analysis criterion would include two risk-related indicators.

E.g. AnalysisCriterion could be called by 
double calculate(CommonTimeSeriesIndicatorInterface interface, List<Trade> trades);

**Comment by npapula** [comment]
BTW this would also allow different implementations for TimeSeries, e.g. one that reads values from database when needed.

**Comment by mdeverdelhan** [comment]
Hi,

Thank you for having studied the ta4j architecture that far.

Short answer:
I think it's not worthwhile.

Long answer:
Indeed, `TimeSeries` and `Indicator` both offer access to values by index. So does ArrayList, but I cannot imagine an common interface between them. Or it would be something too generic to be semantically interesting: notice that TimeSeries gives access to Ticks, when Indicator gives access to directly usable values. What should be the name of that interface (`CommonTimeSeriesIndicatorInterface` isn't an option)? Also, should it be implemented by Indicator or Indicator<Decimal>?

`AnalysisCriterion` has been designed to evaluate the performance of a sequence of trades over a TimeSeries. I know it has to be improved given that trades should not necessarily operated on close prices (which is the case nowadays, I'm working on it). However I can't see the interest in calculating e.g. a total profit over an `OnBalanceVolumeIndicator`, which would be possible if I understand what you are suggesting.
As you mentioned I think it would be slightly useful for risk-related criteria, but I don't have any concrete case in mind. Creating a common interface for both TimeSeries and Indicator may make it easier to use in that specific case. But I don't think it would simplify the code.

I agree with you when you say that reimplementations of TimeSeries would be easier. But I don't think I want the users of ta4j going this way. It would come with (again) more and more problems/questions, essentially regarding the indicator caching system. But if someone is enough motivated, TimeSeries can already be extended.

I'm currently working on a huge API change in order to build trading strategies in a easier way and to provide a record/history of previous trades. As usual, even if your proposal seems justified it comes with numerous questions I don't know how to address. For now I don't have enough time to look deeper into it (but I will keep it in mind if priorities change in the future).

Anyway thank you very much for your idea.
