### ISSUE TITLE
Missing 'Period timePeriod' in full Tick constructor

### ISSUE THREAD

**Issue by lequer** [mdeverdelhan/ta4j#36]
Hello, this is the first time I send an issue, let me know if this is not the right place:

In the complete Tick constructor, the period is always set to days(1). I need to be able to set the period in the constructor as the same time as the prices. Yet I cannot override the field as it is set to private.
```java
public Tick(DateTime endTime, Decimal openPrice, Decimal highPrice, Decimal lowPrice, Decimal closePrice, Decimal volume) {
        this.timePeriod = Period.days(1);
        ...
```
could we have instead
```java
public Tick(DateTime endTime, Period timePeriod, Decimal openPrice, Decimal highPrice, Decimal lowPrice, Decimal closePrice, Decimal volume) {
        this.timePeriod = timePeriod;
        ...
```

**Comment by mdeverdelhan** [comment]
Hi and thank you for your interest,

It's the right place. :)
I'll add the constructor today. It will be in the next snapshot.

**Comment by lequer** [comment]
Thank you. If I wanted to contribute to your project, should I start by trying to resolve issues first?

**Comment by mdeverdelhan** [comment]
You can do what you want.

It's a good idea to start by addressing the already opened issues (notably because it helps me to release a new version sooner).
But you can also propose your own enhancements. If so, you just have to post an issue about it, then we could discuss it before you start your development.

Here you will find a few contribution guidelines: https://github.com/mdeverdelhan/ta4j/blob/master/CONTRIBUTING.md

Thank you.
