### ISSUE TITLE
Make 'Tick' serializable

### ISSUE THREAD

**Issue by the-james-burton** [mdeverdelhan/ta4j#47]
The 'Tick' object is very central to the whole process, but it is not serializable. This means that it could not, for example, be natively serialized and sent over a message bus, such as Rabbit MQ.

I solved this problem myself by extending Tick and making it JSON-marshallable, using Jackson, but do you think it is reasonable for Tick object itself, in Ta4j to also be serializable?

I'm happy to do a PR (with tests) if you think this is worthwhile.

Regards,
James

**Comment by mdeverdelhan** [comment]
Thank you for your interest (and for the PR (with tests) proposal) and sorry for the delay.

I think it's not worthwhile: you found an acceptable way to do what you were looking for and I don't want to enrich ta4j with non-strictly-business-related stuff. Tails (ta4j's father) became unmaintainable because it was full of features that were too far from the original problem (reporting, logging, charting, serialization, and more, and more...) and needed to be tested.

Anyway I really appreciate any idea and PR offer. Again thank you for that.

Marc

**Comment by the-james-burton** [comment]
Hi Marc, that's no problem, I understand. Thanks for taking the time to explain and thanks for this great library!

James
