### ISSUE TITLE
What about specialized strategies?

### ISSUE THREAD

**Issue by ElMoe** [mdeverdelhan/ta4j#51]
For longterm investing there is often a period of time when you just need a buying strategy or a selling strategy - not both at the same time. What about offering specialized strategies for buying and selling seperately with just one argument for the rule set in the constructor?

**Comment by mdeverdelhan** [comment]
I already discussed the specialized-strategies topic somewhere in this issue: https://github.com/mdeverdelhan/ta4j/issues/32
For me it's clearer if we assume that a strategy is a pair of rules: an entry rule and an exit one.
(Please note that an entry signal is not necessarily a BUY, it may be a SELL. It depends on your `OrderType` [here](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L411)).

If you want to have a longer interval between entry and exit, rework your trading rules. I wrote the [`WaitForRule`](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/WaitForRule.java) also for that (however maybe we should update it to work on a time interval instead of a tick count).

If you want to build a strategy that never exit, use [`BooleanRule.FALSE`](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/BooleanRule.java) as your exit rule.

**Comment by ElMoe** [comment]
Thank you for the explications, especially the remark about the BooleanRule.
