### ISSUE TITLE
Contributing enhancements?

### ISSUE THREAD

**Issue by ElMoe** [mdeverdelhan/ta4j#61]
Hi,
i created a bit of code:
- a trailing stop loss indicator
- a class to flexibly convert between common objects of ta4j (jfree-timeseries, ta4j-timeseries, ticklists, indicators etc.) 

I think about contributing the code to the project after some more testing, what do you think?

If ok:
- in which packages would you store the code?
- for the testing of the conversion class i use some real world tick series with different frequencies. Do you have a standard set of time series to test new code or should i also contribute them with the corresponding tests?
- do you have a policy to handle new dependencies to ta4j? For the conversion class it would be needed to add org.apache.commons.math3.stat.* and org.jfree.data.time.* 

Best regards,
E.

**Comment by mdeverdelhan** [comment]
Thank you for your proposal!

Will your trailing stop loss indicator be a boolean indicator? If so, I think you could store it in a `eu.verdelhan.ta4j.indicators.signals` package (to be created). If it is a Decimal one, put it into the `eu.verdelhan.ta4j.indicators.trackers`. I am permissive with the organization of indicators since in numerous cases I don't know where to put them. I think a bit of reordering would be useful.

I am less enthusiastic about your conversion class. For now ta4j has just one dependency (joda-time). Adding commons-math3 and jfree stuff just for that would embarrass me. Ta4j is initially a fork of [Tail](http://tail.sourceforge.net/) which was, according to me, a little messy because it was providing numerous concepts/features. I decided to keep ta4j focused on indicators, backtesting, and raw trading. Furthermore I would not know why I would add a converter to jfree-timeseries and not to what_lib_you_want-timeseries.
So I prefer to think about modifying the current architecture to be more generic (maybe by re-adding several interfaces) instead of adding more and more features to take into account such-and-such a case.

Marc

**Comment by ElMoe** [comment]
The trailing stop loss indicator is a Decimal one, so i'll put it into '.trackers'.

For the conversion class: i already expected that your not that enthusiastic about new dependencies (i would not be either). As far as i know the jfree time series is the only serious Java timeseries class and jfree chart is on the other hand the most commonly used charting library. So i think there may be people using ta4j who can benefit from such a class. But i fully understand why you want to keep it out of ta4j. I'll do some more testing and maybe i'll put it separately on github. Then we could reenter the discussion. 

Best regards,
E.
