### ISSUE TITLE
ema calculation

### ISSUE THREAD

**Issue by diego1982chile** [mdeverdelhan/ta4j#68]
Hi,

I tried to implement macd strategy on ta4j. For doing so, i built this expression (as suggested on issue xxx,) 

```
TimeSeries series = CsvTicksLoader.loadMT4Series("EURUSD_diario_ejemplo3.csv");
buildCandleStickChart(series);
ClosePriceIndicator closePrice = new ClosePriceIndicator(series);

MACDIndicator macd= new MACDIndicator(closePrice,12,26);
EMAIndicator ema= new EMAIndicator(closePrice,9);

Rule entryRule1 = new CrossedUpIndicatorRule(macd,ema);                
Rule exitRule1 = new CrossedDownIndicatorRule(macd,ema);

Strategy strategy1 = new Strategy(entryRule1, exitRule1);                       
        
TradingRecord tradingRecord1 = series.run(strategy1);

System.out.println("Number of trades for our strategy: " + tradingRecord1.getTradeCount());
```

When i run this program, this is thrown throught output console

![image](https://cloud.githubusercontent.com/assets/828287/12825589/ddce659a-cb55-11e5-9b1d-23a0e45d83e2.png)

As can be seen, this strategy performs 0 trades on the time serie. But it seems it should had 
performed several trades, as we can see on the figure below, which ilustrates Meta Trader 4 
macd strategy, in which multiple signals appear along the time serie considered

![image](https://cloud.githubusercontent.com/assets/828287/12825377/c424bf28-cb54-11e5-93e4-d1a4fea55b7f.png)

Doing a deeper comparation, i did some outputting on the indicators. For example, on the first clear signal, which happens at

![image](https://cloud.githubusercontent.com/assets/828287/12826240/d7064c52-cb58-11e5-9aa0-02114240b2e5.png)

**Comment by mdeverdelhan** [comment]
Are you using the `0.7`? If so please update to `0.8-SNAPSHOT` and see issue #39.

If you are already using the `0.8-SNAPSHOT` then your problem may have various causes:
  * The calculations of some indicators are controversial. Providers like ta4j, ta-lib, MT4, etc. are using different ways to compute them. Thus there may be differences between the results you get.
  * There may be a bug in the EMA calculation.
  * There may be a bug in the MACD calculation.
  * There may be a bug in the `CrossedUpIndicatorRule`.
  * There may be a bug in the `CrossedUpIndicatorRule`.
  * There may be a bug in the strategy runs.

Unfortunately I don't have enough time to investigate on each potential origin.

In order to help you, you should:
  * Work with [subseries](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L290), on series slices where you think you should enter or exit.
  * Activate the logs and trace the execution of your strategy (see https://github.com/mdeverdelhan/ta4j/wiki/Usage%20examples#logging)

**Comment by diego1982chile** [comment]
Hi,

Thank's for yor quick reply mdeverdelhan, i will check the steps you point...

I am using the 0.8 snapshot,

I wasn't able to finish my first post at the moment, but because you already
answered it, so just to clarify the issue i am going to continue here...

As we get closer to the first crossing point, the values of the macd and signal (ema) 
tend to be equal, as ilustrated on figures below

![image](https://cloud.githubusercontent.com/assets/828287/12849144/d106c422-cbfc-11e5-8f95-3aae8d61a90c.png)

![image](https://cloud.githubusercontent.com/assets/828287/12849153/da838a3a-cbfc-11e5-9902-e1a0af6ffa19.png)

As i was saying, i did some ouputting on the indicators, and this is what ta4j outputs near
to the corresponding crossing point:

![image](https://cloud.githubusercontent.com/assets/828287/12849181/06ef813c-cbfd-11e5-887d-98268188adce.png)

As can be seen in the figure above, macd is showing correct values, but the ema is always above 1 wich is far away from the macd indicator, so i think the issue is bounded to the ema calculation

I will check the steps you point

Regards and Thanks

**Comment by mdeverdelhan** [comment]
Your example is the EUR/USD ratio. The last time EUR was below USD was on July 15, 2002. A 9-days EMA on the close price will always be superior to 1.0 in 2015. ;)
It seems there is a scale change with the MT4 version.

**Comment by diego1982chile** [comment]
mdeverdelhan,

thank you...i didn't note that, excuse me...

**Comment by mdeverdelhan** [comment]
No worries. I'm still interested in knowing why MT4 is shifting the EMA.

**Comment by RuralHunter** [comment]
It seems the calculation of EMA is wrong. I don't know why SMA is involved in the code:
`@Override
    protected Decimal calculate(int index) {
        int startIndex = Math.max(0, index - timeFrame + 1);
        Decimal emaValue;
        if (startIndex == 0) {
            // If the timeframe is bigger than the indicator's value count
            emaValue = indicator.getValue(0);
        } else {
            // Starting point of the EMA
            emaValue = sma.getValue(startIndex);
        }
        
        for (int i = startIndex+1; i <= index; i++) {
            emaValue = indicator.getValue(i).minus(emaValue).multipliedBy(multiplier).plus(emaValue);
        }
        return emaValue;
    }`
According to the definition: https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average
This calculation has nothing to do with SMA

**Comment by mdeverdelhan** [comment]
Hi,

The fact that you don't know why SMA is involved in the calculation of the EMA does not  mean that this calculation is wrong.

Please take 5 minutes to reconsider this sentence from your/Wikipdia's definition of the EMA:
> S1 is undefined. S1 may be initialized in a number of different ways, most commonly by setting S1 to Y1, though other techniques exist, such as setting S1 to an average of the first 4 or 5 observations.
Has the calculation of the EMA really NOTHING to do with SMA?

Read more articles about this indicator, like http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_averages#exponential_moving_average_calculation

Then, please, explain in which way our calculation of the EMA is giving you WRONG RESULTS. If it's because they don't match your other EMA function maybe you should it instead of ta4j's one.

Don't hesitate to point out flaws in our indicators, but think about it before. ;)

Marc

**Comment by lehneres** [comment]
Hi,

well of course one might use the SMA as starting point for the EMA, but in my opionion only once for the very first initalization. What is indeed wrong for me is that the current implementation re-intializes the EMA upon every request by starting the EMA n ticks ago with the SMA and then calculating the EMA. It should rather take the (pre)-calculated EMA from n ticks ago (from CachedIndikator e.g.) and only if it's not available the SMA (or any other valid starting Point)

**Comment by RuralHunter** [comment]
@mdeverdelhan The original code already handled the S1. It is set to Y1 as the doc. The problem is at the start value of other index(greater than 0). The code uses SMA(index-1) which I think is not correct. It should use EMA(index-1). I made this modification and it gives the same result as my other function:
https://github.com/RuralHunter/ta4j/commit/753911ce9b0421c6eedb2f642afcc1e5b3c51133

**Comment by mdeverdelhan** [comment]
@RuralHunter

S1 may be set "to an average of the first 4 or 5 observations" according to your definition. Here is where the SMA is involved. 
For information, ta-lib is using a SMA to initialize the EMA: https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_EMA.c#l285


@lehneres, @RuralHunter

I agree that, ideally, we should always use the previous EMA value. But it would imply that a first call (i.e. when no values are already cached) to `ema.getValue(300)` would recursively call `ema.calculate(300)`, `ema.getValue(299)`, `ema.calculate(299)`, `ema.getValue(298)`, `ema.calculate(298)`, `ema.getValue(297)`, ... over the whole time series. It was the previous EMAIndicator implementation (in 0.7: https://github.com/mdeverdelhan/ta4j/blob/ta4j-0.7/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/trackers/EMAIndicator.java#L49) and it generated `StackOverflowError`s during initialization phases (see #60).

We could imagine another solution that would use the current implementation only if the previous EMA value is not calculated. But again it would imply a behavior I want to avoid: the results of the EMA would depend on the first getValue(index) you would have called. For instance:
  * 1st run: ema.getValue(50); ema.getValue(70);
  * 2nd run: ema.getValue(20); ema.getValue(70);
Both `ema.getValue(70)` calls would return different results.

If you want an more precise EMA I advice you to increase the time frame.

**Comment by lehneres** [comment]
@mdeverdelhan this is my solution which works ok for me and gives the same results as comperable excel implementations

https://gist.github.com/lehneres/8706fbe7a99b0e4f0915

**Comment by mdeverdelhan** [comment]
Again, that way:
  * You removed any SMA, which is the most common seed for the EMA;
  * In the initialization phase you will get a StackOverflowError if your time series have a certain number of ticks.

I'm still looking for a better design.

**Comment by RuralHunter** [comment]
@mdeverdelhan OK, I understand your point. StackOverflowError could happen if we use recursive call to get the previous ema value with very large number of ticks. However, I don't think it would happen with a reasonable number of ticks. I tested data with 1000 ticks and it runs fine. Even with a very large number of ticks, we could adjust the JVM parameter -Xss to set larger stack memory to meet the requirement since this is a limited recursive call.

**Comment by mdeverdelhan** [comment]
I came back to the old EMA implementation. I created a RecursiveCachedIndicator to deal with StackOverflowErrors. It may be improved but it will do the job for now.

**Comment by diego1982chile** [comment]
Hi,

I just realized i was wrong:

The strategy i built was:

```
MACDIndicator macd= new MACDIndicator(closePrice,12,26);
EMAIndicator ema= new EMAIndicator(closePrice,9);

Rule entryRule1 = new CrossedUpIndicatorRule(macd,ema);                
Rule exitRule1 = new CrossedDownIndicatorRule(macd,ema);

Strategy strategy1 = new Strategy(entryRule1, exitRule1);
```

but it should had been

```
MACDIndicator macd= new MACDIndicator(closePrice,12,26);
SMAIndicator sma= new SMAIndicator(macd,9);

Rule entryRule1 = new CrossedUpIndicatorRule(macd,ema);                
Rule exitRule1 = new CrossedDownIndicatorRule(macd,ema);

Strategy strategy1 = new Strategy(entryRule1, exitRule1);
```

Now the strategy performs several trades, as expected..

I offer my apologies for any confusion that i may had provoked

Thanks
