### ISSUE TITLE
Question on calculating indicators using a period instead of a timeframe

### ISSUE THREAD

**Issue by junajo10** [mdeverdelhan/ta4j#87]
Hi,

I would like to know if there is some example that use a concrete period instead of a timeframe. 
I use tick data time serie, but i want to calculate EMA using tick data timeserie + period 10 mins (no timeframe).

EMA(timeserie,N mins period)-> Ema will use different different timeframe. it depends on each minute.
Example: N = 10 mins
Minute 1 to 10 mins: 250 ticks-> EMA will use 250 ticks
Minute 11 to 20 mins:300 ticks -> EMA will use 300 ticks
......

Rgds,

JJ

**Comment by mdeverdelhan** [comment]
Hi,

[Sorry for the delay]

Short answer: no.

Long(est) answer:
Time management would add a huge complexity to the library (and, according to my experience, in all software projects). You have to manage questions around daylight savings, midnight, time origins (UTC, GMT, etc.), timestamping errors, different sources of time, and more, and more...
I don't want to address that kind of problems in ta4j (since I already do in my professional projects).

A dev team I work with would conclude: "Time is Evil".

Marc
