### ISSUE TITLE
Feature discussion: new indicators for longterm trading

### ISSUE THREAD

**Issue by ElMoe** [mdeverdelhan/ta4j#89]
Hi,
i think about implementing a set of indicators which aim at long term trading:

1.) PeriodicalReturnIndicator: 
calculates the absolute return and the return rate in percent over a given period

2.) AnnualizedReturnIndicator: 
specialized version of 1.) for a period of 365 days

3.) ExpectedReturnIndicator: this indicator calulates beginning from the first data point of a given timeseries a new timeseries with values that are calculated with an expected interest rate.

4.) MultiPeriodExpectedReturnIndicator:
This is a generalized indicator of 3.) The idea is to set expected retrun rates for e.g. several years and calulate the new timeseries with these rates

Use case:
a.) Take tick data from an imaginary ETF fund for MSCI World
b.) Get the expected economic growth rate from IWF
c.) ExpectedReturnIndicator with b.)
d.) Calulate AnnualizedReturnIndicator from a.)
e.) Build the following trading strategy: IF AnnulaizedReturnInidcator  FALLS UNDER LOWERBOLLINGERBAND(ExpectedReturnInidcator)  THEN SellSignal

What do you think? Is this worth implementing and contributing to the project?
Best regards,
Elmoe

**Comment by mdeverdelhan** [comment]
Hi,

I think your use case is relevant. But I have some remarks/questions:

  * What would be the difference with your PeriodicalReturnIndicator and the current ROCIndicator?
  * As I said in many issues I don't want to corrupt (I don't use the word lightly) ta4j with what I would call "human-understandable" durations. In your example (365 days): what if it is a leap year? What if the weekends are non-working? Does we have to replace by 260 days? Etc.
  * Your ExpectedReturnIndicator seems pretty simple but maybe I missed something. Would you mind to implement it in one of your branch? It would let me know if it is worthing to add it.
  * Maybe all that stuff would better go to the trading rules part. For instance, your *Return* indicators: what do you mean by "return"? If a price goes from 100 to 80 between indexes 0 and 7, it is likely your "return" will be negative. But what if you sold at 0 and bought at 7? Is it relevant to have a negative return in this case?

Regards,

Marc

**Comment by ElMoe** [comment]
>What would be the difference with your PeriodicalReturnIndicator and the current ROCIndicator?

RateOfChange:
ROC of day t = ClosePrice of day t / ClosePrice of day t minus n days * 100%

Here is a simplified formula for an 'Annualized Return'. It comes from the concept of discounted cash flows. "An annual return, or annualized return, is a percentage value that tells you how much an investment as increased in value on average per year over a period of time." (see [here](http://www.fool.com/knowledge-center/2015/11/28/how-to-calculate-an-annual-return-with-stock-price.aspx)):
Simple Return = (Current Price-Purchase Price) / Purchase Price
Annual Return = (Simple Return +1) ^ (1 / Years Held)-1

Now the PeriodicalReturnIndicator:
Lets say you have close prices of the last three years and you want to calculate the periodical return for a given period of 365 days. The algorithm for the PeriodicalReturnIndicator would do a similar calculation compared to the formula above. If you have three years with a number 1095 days the algorithm would start at day '365' of the 1095 days as day '0':
Simple Return of day '0'= (Price of day '0'- Price of day '-365') / Price of day '-365'
'Rolling 365 day period' return of day '0'= (Simple Return of day '0'+1) ^ (1 / running day number * 365)-1

Then you continue with calculation for day '1' = day '366' of the close prices and so on ...

>As I said in many issues I don't want to corrupt (I don't use the word lightly) ta4j 

Yeah i've read that. I wouldn't make it too complicated and try to take the correct number of days of the specific year into the calculation. For the AnnualReturnIndicator i would take a fixed '365 day period'.

As arguments for the PeriodicalReturnIndicator i would propose a timeseries and a fixed period in days. I would implement then a check in the method, if the timeseries contains enough days to do the calculation. 

> Your ExpectedReturnIndicator seems pretty simple

Yes, in the most simple case of a constant return rate over a whole timeseries it is just one line with a constant slope. But imagine a practical example: if you have an ETF for China then from the point of an expected growth rate you would have expected 10% growth rate per year in the past and now you would expect a growth rate of 6%. So this line would have segments with different slopes. 

You just need that ExpectedReturnIndicator to generate signals by crossing the annualized return. 

>Would you mind to implement it in one of your branch?

If you see a little chance to take over some of the indicators then i would start implementing the indicators and make a demo app. 

>Maybe all that stuff would better go to the trading rules part.Is it relevant to have a negative return in this case?

The periods of negative returns are considered in the concept of discounted cash flows and are important because they hinder the investment to gain value. 

Sorry for the longish answer!
Regards, 
ElMoe

**Comment by mdeverdelhan** [comment]
**PeriodicalReturnIndicator**

OK so your PeriodicalReturnIndicator would just be a `(RoC(365) / 100) - 1`. I don't know if it is worthwhile. Also I don't agree with the name, your PeriodicalReturnIndicator is not "periodical", it is at best "moving" (like the RoC). And in any case, you would have to deal with the following point:

> The periods of negative returns are considered in the concept of discounted cash flows and are important because they hinder the investment to gain value.

There is a misunderstanding.
In what you describe you are considering that your entry operation is a purchase. It may also be a sale, then your return should not be negative in that case.

  0-th tick   |  10-th tick   | return
--------------|---------------|--------
  sell at $10 |  buy at $20   | negative
  sell at $20 |  buy at $10   | positive
  buy at $10  |  sell at $20  | positive
  buy at $10  |  sell at $20  | negative
  
In your formula: Simple Return = (Current Price-*X*) / *X*
The sign of "Simple Return" should depend on if *X* is a purchase price or a sale price.


**AnnualReturnIndicator**

This one is more interesting. I don't want to set an arbitrary duration like the year. It should be parametrized. It might be called "PeriodicalReturnIndicator". It is not "periodic" either, but we would have to add a semantic notion for the period. You could add a default constructor with a timeframe of 365. It would also remove any human day/period concept and would rely only on ticks.

But I still don't understand how you get the "running day number" at index t-th.


**ExpectedReturnIndicator and MultiPeriodExpectedReturnIndicator**

Same thing as above. I think that they can be merged. And also I don't know how you could set that you expect 10% growth rate per year for the 3 next years and then a growth rate of 6% for the subsequent years.


**Misc**

It might be interesting if you could use the real purchase price (in your example strategy) but, for now, there is no mechanism to give it to indicators in ta4j. You don't even know the sale/purchase indexes. That's why I was suggering to put all this logic to the "trading rules" part (which do know these indexes with the `TradingRecord` object).
It's approximately what is done in CashFlow: https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/analysis/CashFlow.java (which is not an indicator because it has to know the trade indexes)

**Comment by ElMoe** [comment]
For the merging of the Indicators and your comments on the parameters i agree.

> There is a misunderstanding. In what you describe you are considering that your entry operation is a purchase. It may also be a sale, then your return should not be negative in that case.

I also feel that there's a misunderstanding ;-) When you speak of entry operation sale / purchase: do you want this initial situation to be considered in the return calculation? This is an interesting point. Then you would need additional information (e.g. the trading records) to calculate this.

I think we talk about two different concepts:

1. Simple Indicator based signal generation by analyzing the crossing of a "performance" graph and a "expected return" graph. ("my intention")
2. The evaluation of the return of all cashflows compared to an expected return rate. ("your intention")

I think the both approaches are valuable. 

"2" would be the classical "discounted cashflow" approach. I think there you need a trading record and the cash flows, which are already existing in the library. With "2" you would get a real good evaluation of your investment. 

"1" would be just needed to get out of an investment e.g. when the current performance is under your expectations as "exit strategy".

**Comment by mdeverdelhan** [comment]
OK that's clearer now. I understand what you want.

In a perfect world I would say that "2" is far more valuable. It would allow the adding of several useful non-trivial indicators. We could turn the hybrid CashFlow object into a real indicator. We could manage investments more finely. Etc.
But it's in a perfect world. Such a solution would imply to re-think/re-design/re-factor/re-test the whole indicator logic. It would raise several questions. We would have to deal with the additional design complexity. Etc.

If you feel motivated enough I prefer "2".
If you have better things to do (which I understand), I will be glad to accept a PR containing the solution "1" and the other indicators (merged). :)

**Comment by ElMoe** [comment]
Alright then! I am interested the both topics ;) At first i have to look closer into the source code. In case of questions i'll use the issue tracker.

**Comment by ElMoe** [comment]
I have one question while trying a few things out: In the Decimal class is only an implementation of pow(n integer). I need an implementation of pow(y float). What's the preferred way in this case?
- Use math.pow() instead and convert into Decimal?
- Implementing a Decimal solution like [here](http://stackoverflow.com/a/3590314)?

**Comment by mdeverdelhan** [comment]
What is the concrete use case? I don't know any indicator for which a float exponent would be needed. Often it is rounded to the nearest integer.
Anyway I would use Math.pow(...) (for rapidity) and then convert into Decimal. For now I don't know any good solution. One way you compute the operation quickly but it leads to imprecision. The other way you get a more exact result but your execution time and your memory consumption are huge.

**Comment by ElMoe** [comment]
>What is the concrete use case? I don't know any indicator for which a float exponent would be needed. 

This topic is affecting both szenarios "1" and "2" from above. Example: Let's say you do the indicator calculation for a timeseries with end-of-day ticks of 11,3 years, then you have the formula from above:

Annual Return = (Simple Return +1) ^ (1 / Years Held)-1

With pow(y float) you could just take y = 11,3 as "Years Held" within the calculation. There are some other more complicated possibilities to do this but I think i'll go for Math.pow(...) for the first shot and then we can have closer look on the indicator. Thanks for answering.

**Comment by ElMoe** [comment]
I have added two new indicators to my forked ta4j repository for concept "1":
[GrowthRateIndicator](https://github.com/ElMoe/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/statistics/GrowthRateIndicator.java)
[StepFunctionIndicator](https://github.com/ElMoe/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/simple/StepFunctionIndicator.java)
They are tested! Please have a look, if it is ok for you - then i would send a PR.

**Comment by mdeverdelhan** [comment]
Erf... That's far from OK.

**About the StepFunctionIndicator**
It's already existing and called FixedDecimalIndicator. Eventually you would have to add a constructor but it has exactly the same behavior. By the way you implemented a very complex solution for managing indexed values. A simple Decimal[] (or better: T[] like in FixedIndicator) would have been enough.

**About the GrowthRateIndicator**

```
for (int i = 1; i <= completeTimeframes; i++)
{
	Decimal currentReturn = this.getValue(i*completeTimeframes);
	currentReturn.plus(Decimal.ONE);
	totalProduct.multipliedBy(currentReturn);
}
totalProduct.pow(completeTimeframes);
```

You say you tested that but I can assure you that it does not do what you expect. (Tip: Decimal is immutable)

You made a 3-in-1 indicator. I don't like that because:
  * we have to manipulate an ugly "calculationMode" (btw an Enum would have been relevant here)
  * in some case you execute some calculations that are not used at the end (which is aberrant from a performance point of view)
  * it decreases the readability of the code (also not respecting the standard Java code conventions does not help)

I am suspicious about the field "savedLastTimeframeresult". Don't forget that your indicator may be used this way:
```
yourGrowthRateInd.getValue(200);
yourGrowthRateInd.getValue(100);
yourGrowthRateInd.getValue(150);
```
Is the value of the "savedLastTimeframeresult" still correct in thatcase?

And in many ways your code is a performance killer (System.out, unnecessarily executed portions of code, useless statements, etc.).

For now I did not look deeply in the calculations themselves.

**Comment by ElMoe** [comment]
Hey Marc,
please don’t close that topic - i am still working on it. The implementation of all the remarks of your last comment require a lot of reorganisation.
Regards,
Elmoe

**Comment by ElMoe** [comment]
Hi, 
here is my final suggestion: [PeriodicalGrowthRateIndicator.java](https://github.com/ElMoe/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/statistics/PeriodicalGrowthRateIndicator.java)
I left out all the unnecessary details and options and simplified the code and I wrote a lot of comments in the code to explain the calculations. 

What you may not like is that the [test](https://github.com/ElMoe/ta4j/blob/master/ta4j/src/test/java/eu/verdelhan/ta4j/indicators/statistics/PeriodicalGrowthRateIndicatorTest.java) needs a separate csv-file for the data, or is it ok for you?
Any suggestions?

**Comment by mdeverdelhan** [comment]
It seems better, and especially much simpler.

Some remarks:

1) You can replace your useless `getMaxItemCount()` method by a call to `getTimeSeries().getTickCount()`.

2) Are you sure you want to return `Decimal.NaN` if the index is below the time frame? Have you tested your indicator in a simple trading strategy? Check if you can find a value for this degraded mode (`Decimal.ONE` for instance). If you are self-confident keep it as-is, but think twice about it (and about the potential usages of your indicator) before.
	
3) I am not against a separate CSV file but:
  * it would have to be placed in `src/test/resources/eu/verdelhan/...`
  * yours is too long. Please keep it as small as possible. It improves the maintainability of the tests.
  * since you can test your indicator with only 10 or 20 values (ticks), you can directly put them in the Java test class.

Except for those points above and for some stylistic mistakes I think it can be merged.

**Comment by ElMoe** [comment]
Ok, here is what i've done:
1) and 3):  I made the changes according your remarks above.
2): I made a few tests and i still want to return NaN values, because i.e. in the US it is not allowed to calculate total returns from incomplete timeframes. I tested this with JFreeChart and i also added a third test into the test file for rules & strategies. In JFreeChart 'NaN' values are perfectly left out of the graphs. For the rules & strategies it also works but if you have several trades and finally a trade with a "buy", then a 'NaN' because of an incomplete timeframe at the end of a series will be regarded as a "selling" point. I think this OK to close the trade but it comes from the ta4j strategy implementation.

**Comment by mdeverdelhan** [comment]
About NaN and strategies, the question was not: does it work? But: is it relevant?

NaN is more often used for weird cases (typically: division by zero). In a complex strategy, with several rules and/or indicators involved, that value is immediately propagated. Then it may lead the user to look for errors where there isn't. I merge it and give it a try. We will update this later if necessary.
