### ISSUE TITLE
RSI and Stochmatic not same as in metatrader

### ISSUE THREAD

**Issue by Nique** [mdeverdelhan/ta4j#90]
When I add

```
RSIIndicator  rsi = new RSIIndicator(closePrice, 14);
System.out.println("RSI: " + rsi.getValue(50));
```

And compare it with RSI(14) in Metatrader the value in ta4j is off by 8 (!!) percent.

The Bollingerbands and CCI indicators are equal to Metatraders Indicators.
So that's working fine.

I use the exact same data ([available here](https://gist.github.com/Nique/25588518f85f7036e069672297f62516)). I actually exported it from Metatrader. What is going on here? Can I rely on this library? Am I doing something wrong here?

How can I get the exact same values as in Metatrader?

[See comparison here](http://i.imgur.com/fM4n8BZ.png)

I found out that the RSI calculation made in TA4J is based on cumulatedGains/cumulatedLosses in the timeframe specified by the user. I think that Metatrader's and simple excel formula's are based on the calculation of just 2 ticks, check if the newer one is bigger, if yes; subtract the old from the new. `up = (i>(i-1)) ?  i-(i-1) : 0;`. The same is done with TA4J except that TA4J is doing it for all 14 ticks back (when given timeframe is 14). This is probably more precise :).

I'm not sure about this. Can someone confirm? I'm building a auto-trader. So it's kinda important.

**Comment by mdeverdelhan** [comment]
Hi,

In the Stockcharts article (http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi) the formula for the average gain is:

  * First Average Gain = Sum of Gains over the past n periods / n
  * Average Gain = [(previous Average Gain) x (n-1) + current Gain] / n
	
Our formula is always:

  * Average Gain = Sum of Gains over the past n periods / n
  
Likely the differences come from that. The Stockcharts article talk about their "smoothing" technique twice.
You are facing a problem I encounter very often: who is right? Maybe them, maybe us, maybe someone else... Or maybe everyone since there is no consensus on the topic.

If ta4j's formula has to be updated:

  * please double-check before and provide some pointers in references
  * make your updates (including unit tests) and send a PR
  
Thank you!

Marc

**Comment by Nique** [comment]
Thanks for your explanation. I haven't dived in to that matt(h)er to understand the concepts off all the indicators. I just noticed that there was a difference :). But I think it is actually a good thing to learn. I will read the documents you provided.

**Comment by bukefalos** [comment]
Hi Marc,

I would like to reopen this topic, since I believe calculation of RSI should be somehow updated to support "smoothing" 
When I look at ta4j RSIIndicator.class javadoc it says: 
```
Relative strength index indicator.
see http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi
```
Which is confusing, because ta4j is not following smoothed calculation that it is referring to. 

Moreover
- 	yahoo.finance is using smoothed RSI (from observation, even though they are not saying it explicitly)
- 	bachart distinguishes from RSI and modified RSI. 
**_Relative Strength Modified Index_** is based on traditional moving average (current RSI implementation in ta4j) http://old.barchart.com/education/std_studies.php?what=std_rsi_mod#study
**_Relative Strength Index_** is based on accumulative moving average (smoothing) http://old.barchart.com/education/std_studies.php?what=std_rsi#study
- 	smoothed calculation was originally used by Wilder (creator of RSI) see original paper http://books.mec.biz/tmp/books/218XOTBWY3FEW2CT3EVR.PDF page 63


Because calculation of smoothed RSI can differ so much from current calculation (from my observations even 38% - see RSI(14) for GOOG on 18/5/2016 60 avg vs 43 smoothed), before I send PR, I would like to have your input. Some users of ta4j may use this indicator and new version can lead to different values and can break their models. 

Should the solution be backward compatible?
Should users of ta4j be able to use also non-smoothed version?

What do you think?

**Comment by mdeverdelhan** [comment]
Hi,

Thank you for this investigation. It seems a relevant idea.

> Should the solution be backward compatible?

If it is possible.

> Should users of ta4j be able to use also non-smoothed version?

Yes!

> Maybe we can use barchart's naming and rename current RSI to Relative Strength Modified Index and create new Relative Strength Index. This way ta4j can support both

I would prefer something like RSI (for the current one) and SmoothedRSI (for the new one). I hate too vague terms such as "modified". (Also you may have other ideas.)

Please be sure to put a lot of comments/pointers to explain in which way both RSIs are different.

**Comment by s-kiips** [comment]
Cannot find smoothed RSI Indicator in the library.  I downloaded this library but could not find this indicator. Is there another updated library? If there is another updated one can i get the link please.

**Comment by martinklepsch** [comment]
@s-kiips did you download `0.9-SNAPSHOT`? I think this was merged after the latest stable version `0.8` has been released.

**Comment by s-kiips** [comment]
@martinklepsch yea i got it now. But it seems in this new version there are some changes in the DATETIME constructor of TICKS. I also had to add the jodadate maven dependency. In the previous version it was all going well except RSI but now problem in DATE. What can be the solution?

**Comment by martinklepsch** [comment]
@s-kiips the new version relies on Java 8 and uses `java.time` instead of JodaTime.
