### ISSUE TITLE
Any reason not to move to Java 8?

### ISSUE THREAD

**Issue by dan-lind** [mdeverdelhan/ta4j#93]
Java 6 is roughly 10 years old.
Performance in general has been improved in later versions of the JDK.
Anything in particular that keeps you from upgrading?

**Comment by somid3** [comment]
I think its the man power.

**Comment by mdeverdelhan** [comment]
Some of the reasons that keep me from upgrading:

  * Some of ta4j users are still running java 6.
  * Streams/lambdas/optionals are really nice to work with. But the added value is very low in our case (even in the indicators) since we don't have very complex pieces of code that would need to be more "readable".
  * Performance in general has been improved in Java 8. But lambdas (which are often used with streams) are performance killers by design (inner classes). For now I don't want to support their usage in the indicators.
  * Java 8 don't have any killer feature that would counterbalance those drawbacks.

But I agree: in general all my new projects run on Java 8.
